# Generated by Django 3.0.7 on 2020-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_categori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categori',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
