# Generated by Django 3.0.7 on 2020-06-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='Categori',
        ),
    ]
