# Generated by Django 3.0.7 on 2020-06-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200605_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
