# Generated by Django 3.0.7 on 2020-06-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200606_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categori',
            name='image',
        ),
    ]
