# Generated by Django 3.0.7 on 2020-06-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_course_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
