# Generated by Django 3.0.7 on 2020-06-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20200608_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categori',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
