# Generated by Django 3.0.7 on 2020-06-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200608_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Urun',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='course',
            new_name='urun',
        ),
    ]
