# Generated by Django 3.0.7 on 2020-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categori',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categori',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='categori',
            name='status',
            field=models.CharField(choices=[('Menu', 'Menu'), ('Haber', 'Haber'), ('Etkinlik', 'Etkinlik'), ('Duyuru', 'Duyuru')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
