# Generated by Django 3.0.7 on 2020-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200610_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='price',
        ),
        migrations.AddField(
            model_name='urun',
            name='tip',
            field=models.CharField(blank=True, choices=[('Menu', 'Menu'), ('Haber', 'Haber'), ('Etkinlik', 'Etkinlik'), ('Duyuru', 'Duyuru')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categori',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10),
        ),
    ]
