# Generated by Django 3.0.7 on 2020-06-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20200610_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='finish_time',
        ),
    ]
