# Generated by Django 3.0.7 on 2020-06-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_urun_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='categori',
            name='tip',
            field=models.CharField(blank=True, choices=[('Menu', 'Menu'), ('categori', 'categori')], max_length=10),
        ),
    ]
