# Generated by Django 3.0.7 on 2020-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayarlar',
            name='iletisim',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
