# Generated by Django 3.0.7 on 2020-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ayarlar_iletisim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayarlar',
            name='hakkimizda',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='iletisim',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ayarlar',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
