# Generated by Django 3.0.7 on 2020-06-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200606_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayarlar',
            old_name='phone2',
            new_name='phone_2',
        ),
    ]
