# Generated by Django 3.0.7 on 2020-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200606_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'Cevlandi'), ('False', 'Cevaplanmadi')], default='False', max_length=20),
        ),
    ]
