# Generated by Django 3.0.7 on 2020-06-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200606_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('Yeni', 'Yeni'), ('Okundu', 'Okundu'), ('Cevaplandi', 'Cevaplandi')], default='Yeni', max_length=20),
        ),
    ]
