# Generated by Django 3.0.7 on 2020-06-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200606_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'Yeni'), ('Read', 'Okundu'), ('Closed', 'Cevaplandi')], default='New', max_length=20),
        ),
    ]
